DROP TABLE ANIME CASCADE CONSTRAINT;

CREATE TABLE ANIME (
    ID_ANIME NUMBER(6) CONSTRAINT PK_ANIME_ID PRIMARY KEY,
    TITULO_ANIME VARCHAR(250) CONSTRAINT ANIME_TITULO_NN NOT NULL,
    GENEROS_ANIME_1 VARCHAR(250), -- Gêneros do anime 1
    GENEROS_ANIME_2 VARCHAR(250), -- Gêneros do anime 2
    GENEROS_ANIME_3 VARCHAR(250), -- Gêneros do anime 3
    DATA_LANCAMENTO DATE, -- Data de lançamento
    DATA_DE_FINALIZACAO DATE, -- Data de finalização
    NUMERO_EPS NUMBER(3), -- Número de episódios
    DESCRICAO VARCHAR(500), -- Descrição
    TEMPORADA VARCHAR(100), -- Temporada
    TIPO_ANIME VARCHAR(50), -- Tipo de anime (ex: série, filme, OVA)
    ESTUDIO VARCHAR(100), -- Estúdio de produção
    ORIGEM VARCHAR(100), -- Origem (mangá, light novel, etc.)
    OPENING VARCHAR(250), -- Abertura
    ENDING VARCHAR(250), -- Encerramento
    OBRA_ANTERIOR VARCHAR(250), -- Obra anterior
    PROXIMA_OBRA VARCHAR(250), -- Próxima obra
    RANK_ANIME_GERAL FLOAT(1), --Rank do anime em geral
    NM_PESSOAS_VOTARAM NUMBER(12), -- Quantidade de pessoas que votaram no anime
    POPULARIADADE NUMBER(9), -- A popularidade do anime para a comuniddae
    LOCAL_DE_REPRODUÇAO VARCHAR(250) --A ONDE O ANIME ESTÁ SENDO O REPRODUZIDO
);

CREATE TABLE USUARIO(
    ID_USER NUMBER(6) CONSTRAINT PK_USER_ID PRIMARY KEY, --ID DO USUSARIO
    NOME VARCHAR(255) CONSTRAINT NN_NOME_USER NOT NULL, --NOME DO USUARIO
    NICKNAME VARCHAR(255) CONSTRAINT NN_NOME_USER NOT NULL, -- NICKNAME DO USUARIO
    EMAIL VARCHAR(255) CONSTRAINT NN_EMAIL_USER NOT NULL, --EMAIL DO USUARIO
    PASSWORD_USER VARCHAR(255) CONSTRAINT NN_PASSWORD_USER NOT NULL, --SENHA DO USUARIO
    DTANASC DATE, -- DATA DE NASCIMENTO
    STATUS_DO_USUARIO CHAR(1), --SE O USUARIO ESTÁ ATIVO OU NÃO
);

CREATE TABLE LISTA_DOS_ANIMES_FAVORITOS_DE_CADA_USUARIO(
    ID_DA_LISTA NUMBER(1) PRIMARY KEY,
    NUMERO_DA_LISTA NUMBER(1) UNIQUE,
    ID_USER REFERENCES USUARIO,
    ID_ANIME REFERENCES ANIME,
);

CREATE TABLE SCOREANIME(
    ID_ANIME REFERENCES ANIME,
    ID_USER REFERENCES USUARIO,
    SCOREUSER FLOAT(1) CONSTRAINT PK_SCOREUSER PRIMARY KEY
);

CREATE TABLE STATUS_DO_ANIME_PARA_O_USUARIO(
);

CREATE TABLE NEWS(
);

CREATE TABLE MANGA(
);

CREATE TABLE PERSONAGENS(
);